name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "shahinboss888@gmail.com"
  GitHubName: "noobisjack" 
  Branch: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.HOMEBOT_REPOSLUG }} -b ${Branch} bot
      - name: Home Bot Files
        timeout-minutes: 340
        continue-on-error: true
        run: |
           python3 --version
           sudo apt-get update
           sudo apt install python3 -y
           python3.9 -y exit()
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
           python3 --version
           cd Bot && pip3 install . && python3 -m homebot
