name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "atharv2951@gmail.com"
  GitHubName: "atharv2951" 
  Branch: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.HOMEBOT_REPOSLUG }} -b ${Branch} bot
      - name: Home Bot Files
        timeout-minutes: 340
        continue-on-error: true
        run: |
           sudo apt update
           sudo apt install python3.9
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8.10 1
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
           sudo update-alternatives --config python3
           2
           sudo rm /usr/bin/python3
           sudo ln -s python3.9 /usr/bin/python3
           python3 --version
           cd Bot && pip3 install . && python3 -m homebot
      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
